# Generated by Django 4.1 on 2022-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='num_of_remaining_deliveries',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
