# Generated by Django 4.1 on 2022-08-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_alter_courier_num_of_remaining_deliveries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='courier_id',
            field=models.PositiveIntegerField(),
        ),
    ]
