# Generated by Django 4.1 on 2022-08-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_alter_courier_courier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='num_of_scheduled_deliveries',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
